### ISSUE TITLE
Is quickconnect supported ?

### ISSUE THREAD

**Issue by c0ze** [thavel/synolopy#10]
Sorry not really a bug/issue, just wondering if quickconnect is supported ?

I'm trying to connect to my server via :

```
>>> from synolopy import NasApi
>>> nas = NasApi('https://myID.quickconnect.to/webapi/', 'myUser', 'myPass')
>>> nas.downloadstation.info.request('getinfo')
```

And I get

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/synolopy/cgi.py", line 34, in inner
    return manager.validate(func(*args, **kwargs))
  File "/usr/local/lib/python2.7/site-packages/synolopy/cgi.py", line 147, in request
    session = manager.session(node) or manager.credentials(node)
  File "/usr/local/lib/python2.7/site-packages/synolopy/devices.py", line 35, in credentials
    cookie = _NasValidationManager.validate(resp)
  File "/usr/local/lib/python2.7/site-packages/synolopy/devices.py", line 15, in validate
    rsp = response.json()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

because the response is not json probably. This is related to

https://forum.synology.com/enu/viewtopic.php?f=223&t=131754

Any tips, pointers are appreciated, thanks !

**Comment by idealhack** [comment]
Hi, @c0ze, I'm also facing this problem, how do you end up with it? Port-forwarding might be a must-have for public accesses.
