### ISSUE TITLE
Delete method

### ISSUE THREAD

**Issue by SimWhite** [thavel/synolopy#8]
Hello. I'm really sorry for my previous issue #6 there was my mistake.

But now I get the practically the same error with the _delete_ method.

I'm trying to remove task as `nas.downloadstation.task.request('delete', id='dbid_86')` where the `id` I get from the `list` method as `nas.downloadstation.task.request('list')`.

And as the results I get:

```
Traceback (most recent call last):
  File "X:/tests/synology-ds-test.py", line 32, in <module>
    print nas.downloadstation.task.request('delete', id='dbid_86')
  File "C:\Python27\lib\site-packages\synolopy\cgi.py", line 34, in inner
    return manager.validate(func(*args, **kwargs))
  File "C:\Python27\lib\site-packages\synolopy\devices.py", line 20, in validate
    raise SynologyException(API_ERROR[code])
synolopy.errors.SynologyException: Unknown error
```

**UPD**: `pause` and `resume` methods working fine.

**Comment by SimWhite** [comment]
I missed `force_complete` parameter. Now everything is working fine.
